# Generated by Django 6.0.7 on 2026-08-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='service',
        ),
    ]
